### PR TITLE
Imogen Gelato Fulfillment (WIP)

### PR DESCRIPTION
**Pull request by transfaeries**
- ~~change "fulfillment" to "buy" or "print"~~
- ~~change top up message~~
- ~~say “reply” in instructions~~
- ~~have instructions~~
- upsampling being automatic when someone tries to buy a print

### CODE REVIEW

**Comment by transfaeries** [comment]
"I’d make two lists, one top level with most important 5 commands (buy, imagine, help, etc) then list the “secret menu” as final prompt that’s first level and that opens up all the others."

**Comment by transfaeries** [comment]
Ideal to have the confirmation repeat the prompt

**Comment by transfaeries** [comment]
Also, give them a 30min window to cancel/get refund in next version.

**Comment by technillogue** [comment]
this needs to be against imogen-postgres and not main

**Comment by transfaeries** [comment]
closing then

**Pull request closed without merging**
