### PR TITLE
add send_typing

### PR DESCRIPTION
**Pull request by technillogue**
- add send_typing method
- update evilbot

### CODE REVIEW

**Comment by itdaniher** [comment]
work on auxin? groups?

**Comment by technillogue** [comment]
works on groups, doing this with auxin would require the simulate dance, which i'm hoping will be simpler soon

**Comment by technillogue** [comment]
i tried adding a version for auxin, but i don't know why it doesn't work. can be tested with evilbot

**Review by itdaniher — APPROVED** [review]
awesome

**Pull request merged**
