### PR TITLE
Expand pdictng with support for upstash.com webdis

### PR DESCRIPTION
**Pull request by itdaniher**
3x speedup over postgrest, 10k requests/day free!

Now schemaless, still strongly persistent, still $0 to get started! But now takes ~5min not ~15min to setup a new datastore.

### CODE REVIEW

**Comment by technillogue** [comment]
maybe some notes about redis vs postgres consistency?

**Comment by itdaniher** [comment]
https://docs.upstash.com/redis/features/consistency

check this out

**Comment by technillogue** [comment]
i really want to merge this but i also want pdictng_docs/README.md explaining pAUTH

**Review by technillogue — COMMENTED** [review]
i really want to merge this but i also want pdictng_docs/README.md explaining pAUTH

**Review by technillogue — APPROVED** [review]
looks good to merge, go for it

**Pull request merged**
