### PR TITLE
Confirmations of transactions + notifications of status

### PR DESCRIPTION
**Pull request by iamalwaysuncomfortable**
* Confirmation logic added to

1. Optionally wait until tx is confirmed on the blockchain before sending confirmation
1. Provide a notification to the tx sending code what the status of the tx is

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201632126650504/1201666761691800) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by technillogue** [comment]
I need to merge this before merging #82, right?

**Comment by iamalwaysuncomfortable** [comment]
It needs some fixes - I'll push those now, it can be merged prior to airdrops. Also, merge of airdrops should be halted until we discuss some of the feature changes it proposes

**Comment by iamalwaysuncomfortable** [comment]
@technillogue This pull contains both payment confirmations + fixes to the errors crashing handle_messages for non-data message futures. Those error fixes are already integrated into #82 this commit would add transaction confirmation prior to sending a transaction confirmation message + add transaction status information into the reply. 

There are some conflicts in send_payment method signatures with other bots, but we can agree on a standard method signature.

**Comment by technillogue** [comment]
looks good, I'll merge and add some fixups in my branch

**Pull request merged**
