### PR TITLE
add RNG for covid testing

### PR DESCRIPTION
**Pull request by cxloe**
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1201632126650504/1201643387408849) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by technillogue** [comment]
should this actually be merged into main?

**Comment by itdaniher** [comment]
probably not, but I could see a "roll 1d10000" command making it in as an easteregg

**Comment by itdaniher** [comment]
oh this was a merge to clangat - I'd definitely add a "roll" command to go with rot13 (secret parties need secret tools)

**Comment by itdaniher** [comment]
also going to make sure tickets have short (human-friendly) UIDs and corresponding QR codes (wtih human readable labels) to go along with it

**Comment by itdaniher** [comment]
closed by 9818a84bb33d4a0e38cc3f44fb1601157100e453

**Pull request closed without merging**
